import { readFileSync, existsSync, readdirSync } from "node:fs";
import { defineConfig } from "astro/config";
import starlight from "@astrojs/starlight";
import starlightLlmsTxt from "starlight-llms-txt";
import starlightImageZoom from "starlight-image-zoom";
import starlightLinksValidator from "starlight-links-validator";
import astroMermaid from "astro-mermaid";
import rehypeRelativeMarkdownLinks from "astro-rehype-relative-markdown-links";

// ---------------------------------------------------------------------------
// Site-projection controls live in harness.config.json `.site` (the one file a
// clone edits) so neither the template nor a clone hand-edits THIS file —
// astro.config.mjs stays byte-identical across instances and `copier update`
// never conflicts on it. We read the manifest at config-eval time and branch on
// it. Absent/partial `.site` falls back to: llms-txt + mermaid ON, the two
// optional plugins OFF, primarySurface "auto".
// ---------------------------------------------------------------------------
const BASE = "/research-harness-template";
const cfg = existsSync("./harness.config.json")
  ? JSON.parse(readFileSync("./harness.config.json", "utf8"))
  : {};
const siteCfg = cfg.site ?? {};
const plugins = {
  llmsTxt: true,
  mermaid: true,
  imageZoom: false,
  linksValidator: false,
  ...(siteCfg.plugins ?? {}),
};

// Enumerate the report topics for the sidebar. Every topic dir under reports/ (not
// `_meta`) that holds at least one rendered PAGE becomes ONE sidebar entry linking to
// its README index (`/reports/<topic>/`) — the per-report tree is NOT autogenerated into
// the sidebar (it would clutter); a topic's constituents are navigated from its README
// index page. A page is a `[^_]` markdown file that the content.config.ts loader keeps —
// i.e. anything except the `*-delta.md` / `*-build-spec.md` build logs (README, synthesis,
// falsification report, research-progress, and the genre report-*.md all render).
const REPORT_MD = /\.(?:markdown|mdown|mkdn|mkd|mdwn|md|mdx)$/i;
const NON_PAGE_REPORT_MD = /(?:-delta|-build-spec)\.(?:markdown|mdown|mkdn|mkd|mdwn|md|mdx)$/i;
function isReportPage(f) {
  return REPORT_MD.test(f) && !f.startsWith("_") && !NON_PAGE_REPORT_MD.test(f);
}
function humanizeTopic(slug) {
  return slug.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()).trim();
}
function reportTopics() {
  if (!existsSync("./reports")) return [];
  const out = [];
  for (const d of readdirSync("./reports", { withFileTypes: true })) {
    if (!d.isDirectory() || d.name === "_meta") continue;
    if (!readdirSync(`./reports/${d.name}`).some(isReportPage)) continue;
    const title = (cfg.topics ?? []).find((t) => t.id === d.name)?.title || humanizeTopic(d.name);
    out.push({ label: title, link: `/reports/${d.name}/` });
  }
  return out.sort((a, b) => a.label.localeCompare(b.label));
}
const topics = reportTopics();
const hasReports = topics.length > 0;
const primary =
  siteCfg.primarySurface === "reports" ? "reports"
  : siteCfg.primarySurface === "docs" ? "docs"
  : hasReports ? "reports" : "docs"; // "auto" (or unset)

// The harness docs cross-link each other with relative *.md paths (so they render on GitHub
// too). Starlight 0.41 does not resolve those natively, so we keep rewriting them to built
// routes at build time. The plugin's peer range caps at astro <7, but it functions on astro 7
// (verified by build); a package.json `overrides` relaxes the peer to `$astro`. `collectionBase:
// false` because the `docs` collection is served at the site root, not under /docs.
const docContentGroups = [
  { label: "Tutorials", collapsed: true, items: [{ autogenerate: { directory: "tutorials", collapsed: true } }] },
  { label: "How-to guides", collapsed: true, items: [{ autogenerate: { directory: "how-to", collapsed: true } }] },
  { label: "Reference", collapsed: true, items: [{ autogenerate: { directory: "reference", collapsed: true } }] },
  { label: "Explanation", collapsed: true, items: [{ autogenerate: { directory: "explanation", collapsed: true } }] },
  { label: "Decisions (ADRs)", collapsed: true, items: [{ autogenerate: { directory: "adr", collapsed: true } }] },
];
// Reports group: the Overview index plus ONE link per topic to its README index. The
// topic filter (the Sidebar component override) narrows this list; the per-topic report
// tree lives on each README index page, not here.
const reportsGroup = {
  label: "Reports",
  collapsed: true,
  items: [{ label: "Overview", link: "/reports/" }, ...topics],
};
const ecosystemGroup = {
  // Bidirectional traversal: links OUT of this sub-site back to the org root
  // and the sibling ecosystem surfaces.
  label: "MIF ecosystem",
  collapsed: true,
  items: [
    { label: "MIF home", link: "https://modeled-information-format.github.io/" },
    { label: "Ecosystem docs", link: "https://modeled-information-format.github.io/docs/" },
    { label: "Specification (mif-spec.dev)", link: "https://mif-spec.dev" },
  ],
};
// Reports lead the sidebar when they are the primary surface; otherwise they sit
// after the docs. The MIF-ecosystem links stay last. When there are no reports the
// group is omitted entirely.
const sidebar = !hasReports
  ? [...docContentGroups, ecosystemGroup]
  : primary === "reports"
    ? [reportsGroup, ...docContentGroups, ecosystemGroup]
    : [...docContentGroups, reportsGroup, ecosystemGroup];

const starlightPlugins = [
  ...(plugins.llmsTxt ? [starlightLlmsTxt()] : []),
  ...(plugins.imageZoom ? [starlightImageZoom()] : []),
  ...(plugins.linksValidator ? [starlightLinksValidator()] : []),
];

// reports/ deliverables (README, synthesis, falsification report, research-progress) carry
// a body `# H1` and get their Starlight `title` DERIVED from it by the content loader, so
// Starlight would render the title H1 AND the body H1 — a duplicate. Strip the leading H1
// from any reports/ page so the heading shows once. The genre report-*.md carry a frontmatter
// title and no body H1, so this is a no-op for them. Source files are untouched (markdownlint
// MD025 stays green; the strip is render-only).
function remarkStripReportH1() {
  return (tree, file) => {
    const p = (file && (file.path || (file.history && file.history[file.history.length - 1]))) || "";
    if (!/[/\\]reports[/\\]/.test(String(p))) return;
    const idx = tree.children.findIndex((n) => n.type === "heading" && n.depth === 1);
    if (idx !== -1) tree.children.splice(idx, 1);
  };
}

// The research-harness docs are mounted as a sub-site of the MIF org Pages root,
// the same way doc-site serves /docs. The org Pages shell (…github.io deploy.yml)
// checks this repo out, runs `npm run build`, and mounts dist/ under /research-harness-template.
export default defineConfig({
  site: "https://modeled-information-format.github.io",
  base: BASE,
  markdown: {
    remarkPlugins: [remarkStripReportH1],
    rehypePlugins: [
      [
        rehypeRelativeMarkdownLinks,
        { collectionBase: false, base: BASE, trailingSlash: "always" },
      ],
    ],
  },
  integrations: [
    ...(plugins.mermaid ? [astroMermaid()] : []),
    starlight({
      plugins: starlightPlugins,
      title: "MIF Research Harness",
      // Sidebar override: adds a client-side filter that narrows the Reports topic list.
      components: { Sidebar: "./src/components/Sidebar.astro" },
      customCss: ["./src/styles/mif-brand.css"],
      logo: {
        light: "./src/assets/logo-light.svg",
        dark: "./src/assets/logo-dark.svg",
        replacesTitle: true,
      },
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/modeled-information-format/research-harness-template",
        },
      ],
      sidebar,
    }),
  ],
});
