# GENERATED by scripts/codegen/gen-models.sh from schemas/artifact.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict

type FindingRef = str


class Section(TypedDict):
    heading: str
    body: str
    supports: NotRequired[list[str]]


class Source(TypedDict):
    title: str
    url: str
    citationType: str
    citationRole: str


class Mif(TypedDict):
    conformanceLevel: NotRequired[Literal[1, 2, 3]]


FindingsToArtifactContract = TypedDict(
    "FindingsToArtifactContract",
    {
        "@type": Literal["Artifact"],
        "title": str,
        "subtitle": NotRequired[str],
        "genre": str,
        "audience": NotRequired[str],
        "namespace": NotRequired[str],
        "newsworthiness": NotRequired[Literal["high", "medium", "low"]],
        "finding_refs": list[FindingRef],
        "sections": list[Section],
        "sources": list[Source],
        "mif": NotRequired[Mif],
    },
)
