# GENERATED by scripts/codegen/gen-models.sh from schemas/concordance.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class Node(TypedDict):
    id: str
    kind: Literal["concept", "entity"]
    label: str
    topics: list[str]
    entityType: NotRequired[str | None]
    ontology: NotRequired[str | None]
    verdict: NotRequired[
        Literal["falsified", "weakened", "survived", "inconclusive"] | None
    ]
    flagged: bool
    external: NotRequired[bool]


class Edge(TypedDict):
    source: str
    target: str
    type: str
    via: Literal["relationship", "entity"]
    strength: NotRequired[float | None]


OntologicalSpineConcordance = TypedDict(
    "OntologicalSpineConcordance",
    {
        "@type": Literal["Concordance"],
        "generator": NotRequired[str],
        "nodes": list[Node],
        "edges": list[Edge],
    },
)
