# GENERATED by scripts/codegen/gen-models.sh from schemas/findings.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class Verification(TypedDict):
    verdict: Literal["falsified", "weakened", "survived", "inconclusive"]
    verdict_basis: str
    attempted_at: NotRequired[str]
    disconfirming_evidence: NotRequired[list[str]]


class Harness(TypedDict):
    dimension: str
    verification: Verification
    gathered_under: NotRequired[str]


class Extensions(TypedDict):
    harness: Harness


Entity = TypedDict(
    "Entity",
    {
        "@id": str,
    },
)


EntityReference = TypedDict(
    "EntityReference",
    {
        "@type": Literal["EntityReference"],
        "entity": Entity,
        "entityType": NotRequired[
            Literal["Person", "Organization", "Technology", "Concept", "File"] | str
        ],
        "name": NotRequired[str],
        "role": NotRequired[str],
    },
)


EmbeddingReference = TypedDict(
    "EmbeddingReference",
    {
        "@type": NotRequired[Literal["EmbeddingReference"]],
        "model": NotRequired[str],
        "modelVersion": NotRequired[str],
        "dimensions": NotRequired[int],
        "sourceText": NotRequired[str],
        "vectorUri": NotRequired[str],
        "normalized": NotRequired[bool],
    },
)


class EntityData(TypedDict):
    name: str
    entity_type: NotRequired[str]
    entity_id: NotRequired[str]


OntologyReference = TypedDict(
    "OntologyReference",
    {
        "@type": NotRequired[Literal["OntologyReference"]],
        "id": str,
        "version": NotRequired[str],
        "uri": NotRequired[str],
    },
)


Provenance = TypedDict(
    "Provenance",
    {
        "@type": NotRequired[str],
        "sourceType": NotRequired[
            Literal[
                "user_explicit",
                "user_implicit",
                "agent_inferred",
                "external_import",
                "system_generated",
            ]
        ],
        "confidence": NotRequired[float],
        "trustLevel": NotRequired[
            Literal[
                "verified",
                "user_stated",
                "high_confidence",
                "moderate_confidence",
                "low_confidence",
                "uncertain",
            ]
        ],
    },
)


class Relationship(TypedDict):
    type: str
    target: str
    strength: NotRequired[float]
    metadata: NotRequired[dict[str, Any]]


class Decay(TypedDict):
    model: NotRequired[Literal["none", "linear", "exponential", "step"]]
    halfLife: NotRequired[str]
    currentStrength: NotRequired[float]
    strength: NotRequired[float]
    lastReinforced: NotRequired[str]


class ReinforcementHistoryItem(TypedDict):
    timestamp: str
    event: str
    strengthDelta: NotRequired[float]
    context: NotRequired[str]


TemporalMetadata = TypedDict(
    "TemporalMetadata",
    {
        "@type": NotRequired[Literal["TemporalMetadata"]],
        "validFrom": NotRequired[str | None],
        "validUntil": NotRequired[str | None],
        "recordedAt": NotRequired[str],
        "ttl": NotRequired[str],
        "decay": NotRequired[Decay],
        "accessCount": NotRequired[int],
        "lastAccessed": NotRequired[str],
        "reinforcementHistory": NotRequired[list[ReinforcementHistoryItem]],
    },
)


Citation = TypedDict(
    "Citation",
    {
        "@type": Literal["Citation"],
        "citationType": Literal[
            "article",
            "book",
            "paper",
            "website",
            "documentation",
            "repository",
            "video",
            "podcast",
            "specification",
            "dataset",
            "tool",
            "other",
        ]
        | str,
        "citationRole": Literal[
            "supports",
            "refutes",
            "background",
            "methodology",
            "contradicts",
            "extends",
            "derived",
            "source",
            "example",
            "review",
        ]
        | str,
        "title": str,
        "url": str,
        "author": NotRequired[EntityReference | list[EntityReference] | str],
        "date": NotRequired[str],
        "accessed": NotRequired[str],
        "relevance": NotRequired[float],
        "note": NotRequired[str],
    },
)


Mif = TypedDict(
    "Mif",
    {
        "@context": str | list[str | dict[str, Any]] | dict[str, Any],
        "@type": Literal["Concept"] | Literal["Memory"] | list[Any],
        "@id": str,
        "conceptType": Literal["semantic", "episodic", "procedural"],
        "memoryType": NotRequired[Literal["semantic", "episodic", "procedural"]],
        "timestamp": NotRequired[str],
        "description": NotRequired[str],
        "content": str,
        "title": NotRequired[str],
        "created": str,
        "modified": NotRequired[str],
        "ontology": NotRequired[OntologyReference],
        "entity": NotRequired[EntityData],
        "namespace": NotRequired[str],
        "tags": NotRequired[list[str]],
        "aliases": NotRequired[list[str]],
        "entities": NotRequired[list[EntityReference]],
        "relationships": NotRequired[list[Relationship]],
        "temporal": NotRequired[TemporalMetadata],
        "provenance": NotRequired[Provenance],
        "embedding": NotRequired[EmbeddingReference],
        "citations": NotRequired[list[Citation]],
        "summary": NotRequired[str],
        "compressedAt": NotRequired[str],
        "blocks": NotRequired[dict[str, str]],
        "extensions": NotRequired[dict[str, Any]],
    },
)


class ResearchHarnessFindingMifBacked(Mif):
    citations: list[Citation]
    extensions: Extensions
