# GENERATED by scripts/codegen/gen-models.sh from schemas/goal.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import NotRequired, TypedDict


class Scope(TypedDict):
    in_scope: NotRequired[list[str]]
    out_of_scope: NotRequired[list[str]]
    non_goals: NotRequired[list[str]]


type Dimension = str


class Check(TypedDict):
    id: str
    assertion: str
    verify: NotRequired[str]


class CompletionCondition(TypedDict):
    summary: str
    checks: list[Check]


class Bound(TypedDict):
    max_rounds: NotRequired[int]
    min_dimensions_complete: NotRequired[int]


class Revision(TypedDict):
    rationale: str
    changed: list[str]
    date: str
    alias: NotRequired[str]
    git_sha: NotRequired[str]


ResearchSessionGoal = TypedDict(
    "ResearchSessionGoal",
    {
        "$schema": NotRequired[str],
        "topic": NotRequired[str],
        "goal_statement": str,
        "scope": NotRequired[Scope],
        "dimensions": list[Dimension],
        "completion_condition": CompletionCondition,
        "bound": NotRequired[Bound],
        "version": NotRequired[str],
        "supersedes": NotRequired[str | None],
        "revision": NotRequired[Revision],
    },
)
