# GENERATED by scripts/codegen/gen-models.sh from schemas/mif/ontology.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class Ontology(TypedDict):
    id: str
    version: str
    description: NotRequired[str]
    schema_url: NotRequired[str]
    extends: NotRequired[list[str]]


class Namespace(TypedDict):
    description: NotRequired[str]
    type_hint: NotRequired[Literal["semantic", "episodic", "procedural"]]
    replaces: NotRequired[str]
    children: NotRequired[dict[str, Namespace]]


Relationship = TypedDict(
    "Relationship",
    {
        "description": NotRequired[str],
        "from": NotRequired[list[str]],
        "to": NotRequired[list[str]],
        "symmetric": NotRequired[bool],
    },
)


class ContentPattern(TypedDict):
    pattern: str
    namespace: NotRequired[str]
    namespaces: NotRequired[list[str]]
    suggest_entity: NotRequired[str]
    context: NotRequired[str]


class UnifiedPattern(TypedDict):
    content_pattern: NotRequired[str]
    file_pattern: NotRequired[str]
    suggest_namespace: NotRequired[str]
    suggest_entity: NotRequired[str]


class FilePattern(TypedDict):
    pattern: str
    namespaces: NotRequired[list[str]]
    context: NotRequired[str]
    suggest_entity: NotRequired[str]


class PropertySchema(TypedDict):
    type: NotRequired[
        Literal["string", "number", "integer", "boolean", "array", "object", "null"]
    ]
    description: NotRequired[str]
    format: NotRequired[str]
    pattern: NotRequired[str]
    items: NotRequired[dict[str, Any]]
    enum: NotRequired[list[Any]]


class Discovery(TypedDict):
    enabled: NotRequired[bool]
    confidence_threshold: NotRequired[float]
    content_patterns: NotRequired[list[ContentPattern]]
    file_patterns: NotRequired[list[FilePattern]]
    patterns: NotRequired[list[UnifiedPattern]]


class Schema(TypedDict):
    required: NotRequired[list[str]]
    properties: NotRequired[dict[str, PropertySchema]]


class EntityType(TypedDict):
    name: str
    description: NotRequired[str]
    base: Literal["semantic", "episodic", "procedural"]
    traits: NotRequired[list[str]]
    schema: NotRequired[Schema]


class Trait(TypedDict):
    description: NotRequired[str]
    extends: NotRequired[list[str]]
    fields: NotRequired[dict[str, PropertySchema]]
    requires: NotRequired[list[str]]


class MifOntologySchema(TypedDict):
    ontology: NotRequired[Ontology]
    namespaces: NotRequired[dict[str, Namespace]]
    entity_types: NotRequired[list[EntityType]]
    traits: NotRequired[dict[str, Trait]]
    relationships: NotRequired[dict[str, Relationship]]
    discovery: NotRequired[Discovery]
