# GENERATED by scripts/codegen/gen-models.sh from schemas/pack.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class Mif(TypedDict):
    exempt: NotRequired[bool]
    reason: NotRequired[str]


class Author(TypedDict):
    name: NotRequired[str]


class Provides(TypedDict):
    skills: NotRequired[list[str]]
    agents: NotRequired[list[str]]
    commands: NotRequired[list[str]]
    dimensions: NotRequired[list[str]]
    genres: NotRequired[list[str]]
    channels: NotRequired[list[str]]
    ontologies: NotRequired[list[str]]


class ResearchHarnessPackClaudeCodePlugin(TypedDict):
    name: str
    version: str
    description: NotRequired[str]
    kind: Literal["methodology", "genre", "channel", "ontology"]
    mif: NotRequired[Mif]
    license: NotRequired[str]
    author: NotRequired[str | Author]
    keywords: NotRequired[list[str]]
    provides: NotRequired[Provides]
