# GENERATED by scripts/codegen/gen-models.sh from schemas/session-state.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import TypedDict


class Finding(TypedDict):
    id: str
    dimension: str
    valid: bool
    attempted_at: str | None
    verdict: str | None


class Dimensions(TypedDict):
    total: int
    done: int


class Check(TypedDict):
    check: str
    passed: bool


class SessionStateCheckpoint(TypedDict):
    topic: str
    findings: list[Finding]
    dimensions: dict[str, Dimensions]
    checks: list[Check]
