# GENERATED by scripts/codegen/gen-models.sh from schemas/mif/source-envelope.schema.json — DO NOT EDIT.

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class Source(TypedDict):
    url: str
    fetchedAt: str
    contentType: str


class Harness(TypedDict):
    source: Source


class Extensions(TypedDict):
    harness: Harness


Entity = TypedDict(
    "Entity",
    {
        "@id": str,
    },
)


EntityReference = TypedDict(
    "EntityReference",
    {
        "@type": Literal["EntityReference"],
        "entity": Entity,
        "entityType": NotRequired[
            Literal["Person", "Organization", "Technology", "Concept", "File"] | str
        ],
        "name": NotRequired[str],
        "role": NotRequired[str],
    },
)


class Hash(TypedDict):
    algorithm: str
    value: str


DocumentReference1 = TypedDict(
    "DocumentReference1",
    {
        "@type": Literal["DocumentReference"],
        "id": NotRequired[str],
        "documentType": NotRequired[
            Literal[
                "pdf",
                "html",
                "markdown",
                "text",
                "transcript",
                "dataset",
                "spreadsheet",
                "presentation",
                "image",
                "audio",
                "video",
                "email",
                "other",
            ]
            | str
        ],
        "url": str,
        "hash": NotRequired[Hash],
        "contentType": NotRequired[str],
        "byteLength": NotRequired[int],
        "version": NotRequired[str],
        "retrievedAt": NotRequired[str],
        "title": NotRequired[str],
    },
)


DocumentReference2 = TypedDict(
    "DocumentReference2",
    {
        "@type": Literal["DocumentReference"],
        "id": str,
        "documentType": NotRequired[
            Literal[
                "pdf",
                "html",
                "markdown",
                "text",
                "transcript",
                "dataset",
                "spreadsheet",
                "presentation",
                "image",
                "audio",
                "video",
                "email",
                "other",
            ]
            | str
        ],
        "url": NotRequired[str],
        "hash": NotRequired[Hash],
        "contentType": NotRequired[str],
        "byteLength": NotRequired[int],
        "version": NotRequired[str],
        "retrievedAt": NotRequired[str],
        "title": NotRequired[str],
    },
)


type DocumentReference = DocumentReference1 | DocumentReference2


EmbeddingReference = TypedDict(
    "EmbeddingReference",
    {
        "@type": NotRequired[Literal["EmbeddingReference"]],
        "model": NotRequired[str],
        "modelVersion": NotRequired[str],
        "dimensions": NotRequired[int],
        "sourceText": NotRequired[str],
        "vectorUri": NotRequired[str],
        "normalized": NotRequired[bool],
    },
)


class EntityData(TypedDict):
    name: str
    entity_type: NotRequired[str]
    entity_id: NotRequired[str]


OntologyReference = TypedDict(
    "OntologyReference",
    {
        "@type": NotRequired[Literal["OntologyReference"]],
        "id": str,
        "version": NotRequired[str],
        "uri": NotRequired[str],
    },
)


class Relationship(TypedDict):
    type: str
    target: str
    strength: NotRequired[float]
    metadata: NotRequired[dict[str, Any]]


class Decay(TypedDict):
    model: NotRequired[Literal["none", "linear", "exponential", "step"]]
    halfLife: NotRequired[str]
    currentStrength: NotRequired[float]
    strength: NotRequired[float]
    lastReinforced: NotRequired[str]


class ReinforcementHistoryItem(TypedDict):
    timestamp: str
    event: str
    strengthDelta: NotRequired[float]
    context: NotRequired[str]


TemporalMetadata = TypedDict(
    "TemporalMetadata",
    {
        "@type": NotRequired[Literal["TemporalMetadata"]],
        "validFrom": NotRequired[str | None],
        "validUntil": NotRequired[str | None],
        "recordedAt": NotRequired[str],
        "ttl": NotRequired[str],
        "decay": NotRequired[Decay],
        "accessCount": NotRequired[int],
        "lastAccessed": NotRequired[str],
        "reinforcementHistory": NotRequired[list[ReinforcementHistoryItem]],
    },
)


type ProvNode = str | dict[str, Any]


Provenance = TypedDict(
    "Provenance",
    {
        "@type": NotRequired[str],
        "sourceType": Literal[
            "user_explicit",
            "user_implicit",
            "agent_inferred",
            "external_import",
            "system_generated",
        ],
        "confidence": NotRequired[float],
        "trustLevel": NotRequired[
            Literal[
                "verified",
                "user_stated",
                "high_confidence",
                "moderate_confidence",
                "low_confidence",
                "uncertain",
            ]
        ],
        "sourceRef": NotRequired[str],
        "agent": NotRequired[str],
        "agentVersion": NotRequired[str],
        "wasGeneratedBy": NotRequired[ProvNode],
        "wasAttributedTo": NotRequired[ProvNode],
        "wasDerivedFrom": NotRequired[ProvNode | list[ProvNode]],
    },
)


Citation = TypedDict(
    "Citation",
    {
        "@type": Literal["Citation"],
        "citationType": Literal[
            "article",
            "book",
            "paper",
            "website",
            "documentation",
            "repository",
            "video",
            "podcast",
            "specification",
            "dataset",
            "tool",
            "other",
        ]
        | str,
        "citationRole": Literal[
            "supports",
            "refutes",
            "background",
            "methodology",
            "contradicts",
            "extends",
            "derived",
            "source",
            "example",
            "review",
        ]
        | str,
        "title": str,
        "url": str,
        "author": NotRequired[EntityReference | list[EntityReference] | str],
        "date": NotRequired[str],
        "accessed": NotRequired[str],
        "relevance": NotRequired[float],
        "note": NotRequired[str],
    },
)


ProvenanceModel = TypedDict(
    "ProvenanceModel",
    {
        "@type": NotRequired[str],
        "sourceType": NotRequired[
            Literal[
                "user_explicit",
                "user_implicit",
                "agent_inferred",
                "external_import",
                "system_generated",
            ]
        ],
        "confidence": NotRequired[float],
        "trustLevel": NotRequired[
            Literal[
                "verified",
                "user_stated",
                "high_confidence",
                "moderate_confidence",
                "low_confidence",
                "uncertain",
            ]
        ],
        "sourceRef": NotRequired[str],
        "agent": NotRequired[str],
        "agentVersion": NotRequired[str],
        "wasGeneratedBy": NotRequired[ProvNode],
        "wasAttributedTo": NotRequired[ProvNode],
        "wasDerivedFrom": NotRequired[ProvNode | list[ProvNode]],
    },
)


Mif = TypedDict(
    "Mif",
    {
        "@context": str | list[str | dict[str, Any]] | dict[str, Any],
        "@type": Literal["Concept"] | Literal["Memory"] | list[Any],
        "@id": str,
        "conceptType": Literal["semantic", "episodic", "procedural"],
        "memoryType": NotRequired[Literal["semantic", "episodic", "procedural"]],
        "timestamp": NotRequired[str],
        "description": NotRequired[str],
        "content": str,
        "title": NotRequired[str],
        "created": str,
        "modified": NotRequired[str],
        "ontology": NotRequired[OntologyReference],
        "entity": NotRequired[EntityData],
        "namespace": NotRequired[str],
        "tags": NotRequired[list[str]],
        "aliases": NotRequired[list[str]],
        "entities": NotRequired[list[EntityReference]],
        "relationships": NotRequired[list[Relationship]],
        "temporal": NotRequired[TemporalMetadata],
        "provenance": NotRequired[ProvenanceModel],
        "embedding": NotRequired[EmbeddingReference],
        "citations": NotRequired[list[Citation]],
        "documents": NotRequired[list[DocumentReference]],
        "summary": NotRequired[str],
        "properties": NotRequired[dict[str, str | float | bool | None]],
        "compressedAt": NotRequired[str],
        "blocks": NotRequired[dict[str, str]],
        "extensions": NotRequired[dict[str, Any]],
    },
)


class MifSourceEnvelopeInboundBoundary(Mif):
    provenance: Provenance
    extensions: Extensions
