import { defineCollection } from 'astro:content';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// Source the harness's canonical Diátaxis docs/ tree (repo root) via the
// `src/content/docs` symlink. Using Starlight's own docsLoader() — rather than a
// raw glob with a custom base — is required for the autogenerated sidebar and
// relative-link rewriting to work: Starlight derives sidebar directories from the
// entry path relative to src/content/docs, not from the loader's base.
export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
