import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

// Source the harness's canonical Diátaxis docs/ tree AND its rendered reports/ outputs
// into the single Starlight `docs` collection. The base is `./src/content/docs` (the
// committed symlink to the repo-root docs/ tree) — the standard content location, which
// the `astro-rehype-relative-markdown-links` plugin relies on to rewrite relative *.md
// cross-links to routes. reports/ is reached via the committed `docs/reports` symlink
// (-> ../reports).
//
// We use a plain `glob()` rather than Starlight's `docsLoader()` only for the report
// exclusions docsLoader's fixed `**/[^_]*` pattern cannot express: its underscore rule
// guards filenames, not directories, so it cannot drop `reports/_meta/`, the per-topic
// `research-progress.md` continuity file, the `findings/*.json`, or a topic's `README.md`
// (a build-topic-readme nav index with an H1 title and no Starlight frontmatter — it would
// fail the docs schema). docs/**/README.md carry frontmatter and stay pages.
//
// Routing and the autogenerated sidebar are unaffected: Starlight derives both from each
// entry's id (path relative to base) — docs keep their root routes, reports route under
// `reports/`. Keep the negations — gate_m23 enforces their presence.
export const collections = {
  docs: defineCollection({
    loader: glob({
      base: './src/content/docs',
      pattern: [
        '**/[^_]*.{markdown,mdown,mkdn,mkd,mdwn,md,mdx}',
        '!reports/_meta/**',
        '!reports/**/research-progress.md',
        '!reports/**/findings/**',
        '!reports/**/README.md',
        // Audit/continuity artifacts (falsification verdicts, delta diffs,
        // build specs) are logs, not pages, and carry no Starlight frontmatter.
        '!reports/**/*-falsification-report.md',
        '!reports/**/*-delta.md',
        '!reports/**/*-build-spec.md',
      ],
    }),
    schema: docsSchema(),
  }),
};
