#!/usr/bin/env bash
# gen-models.sh — regenerate the stdlib TypedDict authoring models from the JSON
# Schemas (schemas/*.schema.json). The emitted JSON is the contract; these models
# make agents author it deterministically from typed dicts instead of hand-composed
# shell JSON (no `jq -n` / `eval` quoting footgun).
#
# Pipeline per schema:  bundle (inline $refs offline, no network)  ->  datamodel-codegen
#                       (typing.TypedDict)  ->  lib/harness_models/<name>.py
#
# Runtime stays pure stdlib; datamodel-code-generator is a dev/build-time tool only,
# pinned and installed into a gitignored venv. Generated modules ARE committed.
#
# Usage:  scripts/codegen/gen-models.sh          # regenerate all
#         CHECK=1 scripts/codegen/gen-models.sh  # fail if regeneration would change committed output
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

DCG_VERSION="0.65.0"
VENV="$ROOT/.venv-codegen"
OUT="$ROOT/lib/harness_models"
BUNDLE="$ROOT/scripts/codegen/bundle_schema.py"

# Schemas that agents author as standalone files (each becomes one module).
SCHEMAS=(
  "schemas/findings.schema.json"
  "schemas/goal.schema.json"
  "schemas/artifact.schema.json"
  "schemas/concordance.schema.json"
  "schemas/pack.schema.json"
  "schemas/session-state.schema.json"
  "schemas/mif/ontology.schema.json"
  "schemas/mif/source-envelope.schema.json"
)

# --- toolchain (pinned, isolated) -------------------------------------------
if [ ! -x "$VENV/bin/datamodel-codegen" ] || \
   ! "$VENV/bin/datamodel-codegen" --version 2>/dev/null | grep -q "$DCG_VERSION"; then
  echo "==> creating codegen venv with datamodel-code-generator==$DCG_VERSION"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install --quiet --upgrade pip
  "$VENV/bin/pip" install --quiet "datamodel-code-generator==$DCG_VERSION"
fi

STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"' EXIT

modname() { # schemas/mif/source-envelope.schema.json -> source_envelope
  basename "$1" | sed 's/\.schema\.json$//; s/-/_/g'
}

DEST="$OUT"
[ "${CHECK:-0}" = "1" ] && DEST="$(mktemp -d)/harness_models"
mkdir -p "$DEST"

for schema in "${SCHEMAS[@]}"; do
  name="$(modname "$schema")"
  bundled="$STAGE/$name.bundled.json"
  python3 "$BUNDLE" "$schema" "$ROOT/schemas" "$bundled" >/dev/null
  "$VENV/bin/datamodel-codegen" \
    --input "$bundled" --input-file-type jsonschema \
    --output-model-type typing.TypedDict \
    --target-python-version 3.12 \
    --formatters black \
    --use-double-quotes \
    --disable-timestamp \
    --custom-file-header "# GENERATED by scripts/codegen/gen-models.sh from $schema — DO NOT EDIT." \
    --output "$DEST/$name.py"
  # datamodel-codegen sources TypedDict from typing_extensions (external). Rewrite
  # to the stdlib typing module (3.12+) so generated modules stay pure stdlib.
  python3 - "$DEST/$name.py" <<'PY'
import re, sys
p = sys.argv[1]; s = open(p).read()
# Drop the PEP 728 `closed=True` kwarg: it is a typing_extensions-only feature and
# stdlib TypedDict rejects it. The closed-object contract (additionalProperties:false)
# is enforced by ajv at validation time, so nothing is lost at runtime.
s = re.sub(r",?\s*closed=True", "", s)
if "from typing import" in s:
    s = s.replace("from typing_extensions import TypedDict\n", "")
    s = re.sub(r"from typing import ([^\n]+)",
               lambda m: "from typing import " + ", ".join(
                   sorted(set([x.strip() for x in m.group(1).split(",")] + ["TypedDict"]))),
               s, count=1)
else:
    s = s.replace("from typing_extensions import TypedDict", "from typing import TypedDict")
open(p, "w").write(s)
PY
  echo "==> $schema -> lib/harness_models/$name.py"
done

# Hand-written, never generated: package init + the deterministic emitter.
[ -f "$OUT/__init__.py" ] || : # preserved by gen; written once by the build author

if [ "${CHECK:-0}" = "1" ]; then
  if ! diff -rq "$OUT" "$DEST" \
        --exclude='__init__.py' --exclude='emit.py' --exclude='__pycache__' >/dev/null; then
    echo "ERROR: generated models are stale — run scripts/codegen/gen-models.sh and commit." >&2
    diff -rq "$OUT" "$DEST" --exclude='__init__.py' --exclude='emit.py' --exclude='__pycache__' || true
    exit 1
  fi
  echo "OK: committed models match a fresh regeneration."
fi
